### ISSUE TITLE
Pending Encounters Report: program selection does not save once filters are applied

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#7130]
## What went wrong? 😲

Noticed when using filters in Pending Encounters report, once the program is selected and filters are saved, the selection does not show when you try and use filters again

https://github.com/user-attachments/assets/197d6420-8a6b-4a30-803a-776cc3bed74d

## Expected behaviour 🤔

Considering we cannot choose multiple programs to filter the report by at the same time, it would make sense just to show the selection? Would be better for the user to see which program encounters they are looking at as well?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure you have Immunization Program & Vaccination Card enabled in your store
2. Go to Reports -> Pending Encounters
3. When filtering, choose a program you want to see pending encounters from
4. Report pops up -> revisit the filters -> your program selection is gone

## Your environment 🌱

- Open mSupply Version: `V2.6.1-RC4`
- Legacy mSupply Central Server Version: `V8.00.11`

- Platform: `Google Chrome (browser for Mac)`

- Database type: `PostgreSQL`

**Comment by roxy-dao** [comment]
Should have been fixed with #6760 ... Works for me locally 👀 

https://github.com/user-attachments/assets/446b473a-305f-4516-834e-74b3b1df14b9

**Comment by marthakeezy** [comment]
Hey @roxy-dao, still not saving the selection for me in `V2.7.0-RC7` :(

**Comment by marthakeezy** [comment]
Still there in V2.7.1

**Comment by jmbrunskill** [comment]
Closing — this is specific to the current front end, which the rewrite replaces. Old-front-end-only: the Pending Encounters argument control writes the program registry's context id but reads back a different key, so the selection cannot round-trip. Reports is rebuilt.

If the same problem turns up in the new front end, please raise it fresh — the screen this was reported against won't be there.

If we've got this wrong, just reopen it!

<sub>Part of the Sep 2026 backlog review (698 open issues), labelled `x. closed - Sep 2026 review` so the whole set stays findable and reversible. The review used automated code analysis — mistakes are possible.</sub>
