### ISSUE TITLE
Prescription screen improve patient detail visibility

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#8693]
## Is your feature request related to a problem? Please describe 👀

Currently important identifiable patient details are hidden in the more button so this makes it difficult to ensure dispensing is done to the correct patient as there are usually different patients with same or similar names. Address is also missing from the details which is another valuable patient identifier.

The next problem is when you do select the more tab, you cannot tell especially on tablet that there are patient details available - not too intuitive that you can scroll as you see this screen:

![Image](https://github.com/user-attachments/assets/972b340e-7275-4d0f-9f6d-71f4d78767d3)

Would suggest for helping enforce safer patient dispensing, make patient details more readily visible during dispensing process (e.g., main screen and item dispensing screen where items are being added)

**Comment by mark-prins** [comment]
triage: this will require some design work, would recommend leaving until the dispensary enhancement changes

**Comment by mark-prins** [comment]
Have added to the design trello board

just to note though, that if you click the edit icon beside the patient name (top of page in the prescription):

<img width="540" height="227" alt="Image" src="https://github.com/user-attachments/assets/50169476-01e6-4921-b779-489075d1059f" />

then you do see all of the patient details

<img width="1361" height="881" alt="Image" src="https://github.com/user-attachments/assets/bd4ee7c1-69a2-4b31-80bd-d42022b91b1f" />

**Comment by andreievg** [comment]
triage, still has needs design, removing needs triage to be slotted in by PO

**Comment by jmbrunskill** [comment]
@roxy-dao @mark-prins I'm moving this to back log as. I don't think it's in PR or has been solved right?

New UI:

<img width="1150" height="316" alt="Image" src="https://github.com/user-attachments/assets/b8586772-a767-42c4-af61-297c0b3aa027" />

**Comment by roxy-dao** [comment]
Yes, hasn't been solved. Still missing some important identifiers like address
